### ISSUE TITLE
Needs Solution

### ISSUE THREAD

**Issue by jmburges** [learn-co-curriculum/flashy-tableviews#1]

**Comment by AnnJohn** [comment]
Iceboxing the issue for now.

**Comment by JimCampagno** [comment]
Deadline: 9/4/15 (Friday)

**Comment by AnnJohn** [comment]
hey @JimCampagno was this fixed. If not, could you just set a new deadline? Thanks

**Comment by JimCampagno** [comment]
@AnnJohn Working on the Learn iOS App until Thursday.  New Deadline for this is Friday, 9/11/15.

**Comment by JimCampagno** [comment]
Complete. Closes #2
